version: '3.9'
services:
  pi-stats:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory into the container
      - /app/__pycache__/  # Prevent pycache from being cached on the host system
    environment:
      FLASK_APP: app.py  # Flask app entry point
      FLASK_ENV: development  # Enable development mode for hot-reloading
      FLASK_DEBUG: 1
    command: flask run --host=0.0.0.0 --port=5000 --reload --debug
