version: '3.9'
services:
  pi-stats:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory into the container
    environment:
      FLASK_APP: app.py  # Flask app entry point
      FLASK_ENV: production  # Set to production
      FLASK_DEBUG: 0  # Disable debug mode
    command: gunicorn --bind 0.0.0.0:5000 app:app
