services:
  pi-stats:
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory into the container (disabled for production)
    environment:
      FLASK_APP: app.py  # Flask app entry point
      FLASK_ENV: development  # Use development mode for local testing
      FLASK_DEBUG: 1  # Enable debug mode only in development
    command: flask run --host=0.0.0.0 --port=5000
